apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./all.yaml

patches:
- path: overlays/kafka.yaml
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: .*-cp-kafka