
nameOverride: ""
fullnameOverride: ""


cp-helm-charts:
    enabled: true
    cp-zookeeper:
        enabled: true
        persistence:
            enabled: false
        servers: 1
        heapOptions: "-Xms256M -Xmx256M"
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        prometheus:
            jmx:
                enabled: false
        image: confluentinc/cp-zookeeper
        imageTag: 5.5.0
        serviceAccount:
            create: true
            name: kafka
    cp-kafka-connect:
        enabled: false
        image: confluentinc/cp-kafka-connect
        imageTag: 5.5.0
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        heapOptions: "-Xms256M -Xmx256M"
        prometheus:
            jmx:
                enabled: false
    cp-kafka-rest:
        enabled: false
        image: confluentinc/cp-kafka-rest
        imageTag: 5.5.0
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        heapOptions: "-Xms256M -Xmx256M"
        prometheus:
            jmx:
                enabled: false
    cp-kafka:
        enabled: true
        persistence:
            enabled: false
        brokers: 1
        heapOptions: "-Xms256M -Xmx256M"
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        prometheus:
            jmx:
                enabled: false
        configurationOverrides:
            "offsets.topic.replication.factor": 1
            "num.partitions": "2"
        serviceAccount:
            create: true
            name: kafka
        image: confluentinc/cp-enterprise-kafka
        imageTag: 5.5.0
    cp-ksql-server:
        enabled: false
        image: confluentinc/cp-ksqldb-server
        imageTag: 5.5.0
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        heapOptions: "-Xms256M -Xmx256M"
        prometheus:
            jmx:
                enabled: false
    cp-control-center:
        enabled: false
        # Deprecated
        image: confluentinc/cp-enterprise-control-center
        imageTag: 5.5.0
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        heapOptions: "-Xms256M -Xmx256M"
        prometheus:
            jmx:
                enabled: false
    cp-schema-registry:
        enabled: false
        resources:
            limits:
                cpu: 200m
                memory: 1028Mi
            requests:
                cpu: 100m
                memory: 512Mi
        heapOptions: "-Xms256M -Xmx256M"
        prometheus:
            jmx:
                enabled: false
        image: confluentinc/cp-schema-registry
        imageTag: 5.5.0