apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml
- smoketest-workflow-template.yaml

patchesStrategicMerge:
- overlays/smoke-test-template.yaml