# Default values for argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

appofapps:
    spec:
        destination:
            server: https://kubernetes.default.svc
        source:
            repoUrl: https://github.com/jrhoward/kube-bootstrap.git
            targetRevision: HEAD

argo-cd:
  enabled: true
  installCRDs: false
