
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-argo-workflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: {{ .Values.local.spec.destination.server }}
  project: default
  source:
    path: terraform/k8s/manifests/kustomize/argo-workflow
    repoURL: {{ .Values.local.spec.source.repoURL }}
    targetRevision: {{ .Values.local.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
