spec:
  template:
    spec:
      containers:
      - name: pointless-pod
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command: ["sh", "-c"]
        args: [ "while true; do echo 'hello' ; sleep 3; done"]