server:
  config:
    repositories: |
      - type: helm
        name: confluent-platform
        url: https://confluentinc.github.io/cp-helm-charts/
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["tar -xzf ${CHART_ARCHIVE} --strip-components=1 && helm dependency build"]
        generate:
          command: ["/bin/sh", -c]
          args: ["helm template ${RELEASE_NAME} . > all.yaml && kustomize build"] 
    
dex:
  enabled: false
