server:
  config:
    # repositories: |
    #   - url: https://github.com/jrhoward/kube-bootstrap
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build"]
        generate:
          command: [sh, -c]
          args: ["helm template --release-name release-name . > all.yaml && kustomize build"] 
dex:
  enabled: false
