server:
  config:
    # repositories: |
    #   - url: https://github.com/jrhoward/kube-bootstrap
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["echo 'hello world'"]
        generate:
          command: [sh, -c]
          args: ["helm template ${RELEASE_NAME} ${CHART_ARCHIVE} > all.yaml && kustomize build"] 
dex:
  enabled: false
