kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
data:
    repositories: |
    - type: helm
      name: argo-cd
      url: https://argoproj.github.io/argo-helm
    - url: https://github.com/jrhoward/kube-bootstrap
 