apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/storax/kubedoom/master/manifest/00namespace.yaml
- https://raw.githubusercontent.com/storax/kubedoom/master/manifest/deployment.yaml
- https://raw.githubusercontent.com/storax/kubedoom/master/manifest/rbac.yaml