server:
  config:
    repositories: |
      - type: helm
        name: cp-helm-charts
        url: https://confluentinc.github.io/cp-helm-charts/
      - type: helm
        name: hashicorp
        url: https://helm.releases.hashicorp.com
      - type: helm
        name: confluent-platform-wrapper
        url: https://jrhoward.github.io/kube-bootstrap/helm-charts/
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["tar -xzf ${CHART_ARCHIVE} --strip-components=1 && helm dependency update ."]
        generate:
          command: ["/bin/sh", -c]
          args: ["helm template ${RELEASE_NAME} . > all.yaml && kustomize build"] 
    
dex:
  enabled: false
